apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"alertman2omi:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"alertman2omi\")].image"}]'
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: alertman2omi
    app.kubernetes.io/component: alertman2omi
    app.kubernetes.io/instance: alertman2omi
  name: alertman2omi
  namespace: alertman3omi
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: alertman2omi
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: alertman2omi
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/alertman3omi/alertman2omi@sha256:b00ae82a27a8a0d4f33df44bf249ed2e619342a058242aad1217d3d4f2328c07
        imagePullPolicy: IfNotPresent
        name: alertman2omi
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30